name: "Build Windows"
on: [push]

jobs:    
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
        - Win32
        - x64
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download LuaJIT
      uses: actions/checkout@v4
      with:
        repository: LuaJIT/LuaJIT
        ref: v2.1
        path: LuaJIT
    - name: Configure MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
    - name: Compile LuaJIT
      working-directory: ./LuaJIT/src
      run: msvcbuild.bat amalg
    - name: Configure
      run: cmake -Bbuild -S. -DCMAKE_INSTALL_PREFIX=%CD%\install -A ${{ matrix.arch }} -DLUA_INCLUDE_DIR=%CD%\LuaJIT\src -DLUA_LIBRARIES=%CD%\LuaJIT\src\lua51.lib
    - name: Build
      run: cmake --build build --config Release --target install
    - name: Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: https-windows-${{ matrix.arch }}.zip
        path: install/https.dll
